export const estadosBrasileiros = [
   { label: "Acre", name: "AC" },
   { label: "Alagoas", name: "AL" },
   { label: "Amapá", name: "AP" },
   { label: "Amazonas", name: "AM" },
   { label: "Bahia", name: "BA" },
   { label: "Ceará", name: "CE" },
   { label: "Distrito Federal", name: "DF" },
   { label: "Espírito Santo", name: "ES" },
   { label: "Goiás", name: "GO" },
   { label: "Maranhão", name: "MA" },
   { label: "Mato Grosso", name: "MT" },
   { label: "Mato Grosso do Sul", name: "MS" },
   { label: "Minas Gerais", name: "MG" },
   { label: "Pará", name: "PA" },
   { label: "Paraíba", name: "PB" },
   { label: "Paraná", name: "PR" },
   { label: "Pernambuco", name: "PE" },
   { label: "Piauí", name: "PI" },
   { label: "Rio de Janeiro", name: "RJ" },
   { label: "Rio Grande do Norte", name: "RN" },
   { label: "Rio Grande do Sul", name: "RS" },
   { label: "Rondônia", name: "RO" },
   { label: "Roraima", name: "RR" },
   { label: "Santa Catarina", name: "SC" },
   { label: "São Paulo", name: "SP" },
   { label: "Sergipe", name: "SE" },
   { label: "Tocantins", name: "TO" }
];
